defaults:
  - model: he-net
  - data: sample

device: cuda:1
seed: 0

batch_size: 64
n_epoch: 50

optim:
  args:
    lr: 0.0
    weight_decay: 0.0001
  scheduler:
    max_lr: 0.0001
    pct_start: 0.2

store:
  log: ./log/bank_logo/training_he2_s.log
  checkpoint: ./weights/bank_logo/he2_s.pt